(()=>{'use strict';if(window.__CR_INC_3_12)return;window.__CR_INC_3_12=true;
const BUILD='CR-CENTRAL-INCORPORACAO-3-12-CANDIDATE-20261003',FAST='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/cr-executive-readonly-v12-1-candidate-20261003?view=public-home',AGENDA='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/cr-agenda-executive-v12-1-candidate-20261003?view=public',FULL='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/cr-executive-readonly-v12-candidate-20261003?view=public-home',BASE='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/centro-operacoes',APP='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/central-atendimento';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),brl=c=>c==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(c)/100);
const state={fast:null,agenda:null,full:null,errors:{},kpiObserver:null,agendaObserver:null},ROUTES=Object.freeze({app:APP+'?mode=app',flows:APP+'?mode=f00',f00:APP+'?mode=f00',f01:APP+'?mode=f01',f02:APP+'?mode=f02',f03:APP+'?mode=f03',f04:APP+'?mode=f04',f05:APP+'?mode=f05',f06:APP+'?mode=f06',f07:APP+'?mode=f07',f08:APP+'?mode=f08',f09:APP+'?mode=f09',finance:BASE+'?open=centro-comando',docs:BASE+'?open=docs',presentation:BASE+'?open=presentation',academy:BASE+'?open=academy',health:BASE+'?open=health',technical:BASE+'?open=technical',admin:BASE+'?open=admin'});
async function get(u){const r=await fetch(u+(u.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||('HTTP '+r.status));return d}
function operationalToday(){const a=state.agenda?.kpis;if(!a)return null;return Number(a.visits||0)+Number(a.executions||0)+Number(a.returns||0)+Number(a.warranties||0)}
function stamp(){const e=$('#crHomeUpdated');if(e)e.textContent='Atualizado '+new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function card(cls,ic,l,v,d,s){return '<article class="cr-op-card '+cls+'"><div class="cr-op-top"><span class="cr-op-icon">'+ic+'</span><span class="cr-op-label">'+esc(l)+'</span></div><div class="cr-op-value">'+esc(v)+'</div><div class="cr-op-detail">'+esc(d)+'</div><div class="cr-op-status">'+esc(s)+'</div></article>'}
function renderKpis(){const h=$('#kpis');if(!h)return;const k=state.fast?.kpis||{},a=state.agenda?.kpis||{};h.innerHTML=[card('blue','⚙','Serviços em andamento',k.services_in_progress?.count??'—','Fonte operacional real','Trello'),card('green','$','Aguardando pagamento',k.awaiting_payment?.count??'—',brl(k.awaiting_payment?.amount_cents),'GestãoClick'),card('purple','▣','Visitas do dia',state.agenda?operationalToday():'—',state.agenda?'Google Agenda':'Google Agenda indisponível','Hoje'),card('orange','▤','Agenda amanhã',k.agenda_tomorrow?.count??'—','Google Agenda','Planejamento'),card('amber','✓','Aguardando acerto',k.awaiting_adjustment?.count??'—',brl(k.awaiting_adjustment?.amount_cents),'GestãoClick')].join('');stamp()}
function protectKpis(){const h=$('#kpis');if(!h||state.kpiObserver)return;let lock=false;state.kpiObserver=new MutationObserver(()=>{if(lock||!state.agenda)return;const label=[...h.querySelectorAll('.cr-op-label')].some(x=>x.textContent.trim()==='Visitas do dia'),value=[...h.querySelectorAll('.cr-op-card')].find(x=>x.querySelector('.cr-op-label')?.textContent.trim()==='Visitas do dia')?.querySelector('.cr-op-value')?.textContent;if(!label||String(value)!==String(operationalToday())){lock=true;renderKpis();queueMicrotask(()=>lock=false)}});state.kpiObserver.observe(h,{childList:true,subtree:true,characterData:true})}
function time(v){try{return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(new Date(v))}catch{return'—'}}
function renderAgenda(){const p=$('.cr-quick-panel'),h=$('#quick');if(!p||!h)return;p.querySelector('h2').textContent='GESTÃO DA AGENDA';const sub=p.querySelector('.cr-panel-sub');if(sub)sub.textContent='Google Agenda como fonte oficial • Trello e GestãoClick enriquecem os compromissos.';const a=state.agenda;if(!a){h.innerHTML='<div class="cr-inc-state">Agenda indisponível nesta leitura — nenhum zero foi presumido.</div>';return}const it=a.items||[];h.classList.add('cr-inc-agenda');h.innerHTML=it.length?it.slice(0,7).map(x=>'<article class="cr-quick-card cr-inc-agenda-card"><div class="cr-quick-icon">▣</div><h3>'+esc(time(x.starts_at)+' • '+(x.title||x.type||'Compromisso'))+'</h3><p>'+esc([(x.team||[]).join(' + ')||'Responsável não identificado',x.case,x.location].filter(Boolean).join(' • '))+'</p><span class="cr-inc-badge '+(x.incomplete?'warn':'ok')+'">'+esc(x.incomplete?'Informação incompleta':x.type||'Programada')+'</span></article>').join(''):'<div class="cr-inc-state">Nenhum compromisso comprovado para hoje.</div>'}
function protectAgenda(){const h=$('#quick');if(!h||state.agendaObserver)return;let lock=false;state.agendaObserver=new MutationObserver(()=>{if(lock||!state.agenda)return;const bad=[...h.querySelectorAll('h3,.cr-quick-title')].some(x=>/Dashboard Gerencial V4/i.test(x.textContent||''));const shown=h.querySelectorAll('.cr-inc-agenda-card').length,expected=Math.min((state.agenda.items||[]).length,7);if(bad||shown!==expected){lock=true;renderAgenda();queueMicrotask(()=>lock=false)}});state.agendaObserver.observe(h,{childList:true,subtree:true,characterData:true})}
const COLORS={'AGUARDANDO VISITA/AGENDAMENTO':'#0a8cff','EM ELABORAÇÃO':'#3c8fe8','AGUARDANDO ENVIO':'#62a9ee','AGUARDANDO APROVAÇÃO':'#f2b233','EM ANDAMENTO':'#168fb8','RETORNO':'#7b46e8','AGUARDANDO PAGAMENTO':'#16b879','AGUARDANDO ACERTO':'#ff8a24','FINALIZADO':'#138a61','NÃO APROVADO':'#d85b67','CANCELADO':'#93a9bd'};
function renderQuotes(){const p=$('.cr-flow-panel'),h=$('#flowHome');if(!p||!h)return;p.querySelector('h2').textContent='ORÇAMENTOS / SERVIÇOS EM FLUXO';const sub=p.querySelector('.cr-panel-sub');if(sub)sub.textContent='Status reais do GestãoClick • monitoramento executivo, sem escrita operacional.';const btn=p.querySelector('.cr-panel-action');if(btn){btn.textContent='Atualizar dados →';btn.onclick=e=>{e.stopPropagation();refresh()}}const m=state.full?.quotes?.by_status||state.full?.quotes?.status_distribution||{},rows=Object.entries(m).map(([n,v])=>[n,typeof v==='number'?{count:v,total_cents:null}:v]).sort((a,b)=>(b[1].count||0)-(a[1].count||0));h.classList.add('cr-inc-flow');h.innerHTML=rows.length?rows.map(([n,v])=>'<article class="cr-flow-card cr-inc-status" style="--status:'+esc(COLORS[n]||'#93a9bd')+'"><div class="cr-flow-code">'+esc(n)+'</div><div class="cr-flow-active"><b>'+esc(v.count??'—')+'</b> registros</div><div class="cr-flow-state">'+esc(brl(v.total_cents))+'</div><div class="cr-inc-statusbar"><i></i></div></article>').join(''):'<div class="cr-inc-state">'+(state.errors.full?'GestãoClick indisponível nesta leitura — sem zero presumido.':'GestãoClick carregando em segundo plano…')+'</div>'}
function renderPending(){const h=$('#boardSummary');if(!h)return;const p=state.fast?.pending;if(!p||p.source_status==='SOURCE_IN_IMPLEMENTATION'){h.innerHTML='<article class="cr-pending-card cr-inc-pending"><div class="cr-pending-icon">!</div><div class="cr-pending-copy"><h3>Pendências • fonte em implantação</h3><div class="cr-pending-lines"><span>Banco Mestre ainda sem alimentação operacional homologada.</span><span>Exceções técnicas não são convertidas em pendências.</span></div></div></article>';return}h.innerHTML='<article class="cr-pending-card"><div class="cr-pending-icon">▥</div><div class="cr-pending-copy"><h3>Pendências vivas</h3><div class="cr-pending-total">'+esc(p.total_live)+'</div><div class="cr-pending-lines"><span>Fonte operacional identificada.</span></div></div></article>'}
function renderHealth(){const h=$('#homeHealth');if(!h)return;const s=state.fast?.sources||{},rows=[['Banco de Dados',s.database?.ok],['Trello',s.trello?.ok],['Google Agenda',s.agenda?.ok],['GestãoClick',state.full?.sources?.gestaoclick?.ok??null]];h.innerHTML=rows.map(([n,v])=>'<article class="cr-health-card '+(v===true?'ok':'')+'"><div class="cr-health-label">'+esc(n)+'</div><div class="cr-health-value">'+esc(v===true?'Operacional':v===false?'Atenção':'Carregando')+'</div><div class="cr-health-sub">'+esc(v===true?'Fonte disponível':v===false?'Verificar integração':'Sem presumir estado')+'</div></article>').join('')}
function patchReturns(){document.querySelectorAll('a[href]').forEach(el=>{const href=el.getAttribute('href')||'';if(/central-atendimento/.test(href)&&!/return=/.test(href)){try{const u=new URL(href,location.href);u.searchParams.set('return',location.href);el.setAttribute('href',u.toString())}catch(_){}}})}
async function loadFast(){try{[state.fast,state.agenda]=await Promise.all([get(FAST),get(AGENDA)])}catch(e){state.errors.fast=String(e)}renderKpis();renderAgenda();renderPending();renderHealth()}
async function loadFull(){try{state.full=await get(FULL)}catch(e){state.errors.full=String(e)}renderQuotes();renderHealth()}
async function refresh(){await loadFast();await loadFull()}
function boot(){document.documentElement.dataset.crBuild=BUILD;patchReturns();protectKpis();protectAgenda();loadFast();setTimeout(loadFull,80);setInterval(loadFast,30000);window.CR_INC_3_12={BUILD,ROUTES,state,refresh}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()})();