(()=>{'use strict';
if(window.__CR_V6_PATCH)return;window.__CR_V6_PATCH=true;
const API='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/cr-executive-readonly-v6-candidate-20261002';
const MGMT='https://yspuaamokjbrosytqjpg.supabase.co/functions/v1/cr-pending-management-v6-candidate-20261002';
let D=null,FULL=null,painting=false,qfilter='';
const q=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>v==null?'—':String(v);
const money=c=>typeof c==='number'?(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—';
function sess(){try{return sessionStorage.getItem('crGestaoSession')||localStorage.getItem('crGestaoSession')||''}catch(_){return''}}
async function get(url,opt={}){const h={...(opt.headers||{})},s=sess();if(s)h['x-cr-session']=s;const r=await fetch(url,{...opt,headers:h,cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||('HTTP '+r.status));return d}
function kcard(icon,label,value,detail,status,tone){return '<div class="cr-op-card '+tone+'"><div class="cr-op-top"><span class="cr-op-icon">'+esc(icon)+'</span><span class="cr-op-label">'+esc(label)+'</span></div><div class="cr-op-value">'+esc(num(value))+'</div><div class="cr-op-detail">'+esc(detail)+'</div><div class="cr-op-status">'+esc(status)+'</div></div>'}
function pcard(icon,label,value,detail){return '<div class="cr-pending-card"><div class="cr-pending-icon">'+esc(icon)+'</div><div class="cr-pending-copy"><h3>'+esc(label)+'</h3><div class="cr-pending-total">'+esc(num(value))+'</div><div class="cr-pending-lines"><span><i></i>'+esc(detail)+'</span></div></div><div class="cr-mini-bars"><i></i><i></i><i></i><i></i><i></i><i></i></div><button class="btn" type="button" data-v5-open-pending="1">Abrir gestão</button></div>'}
function hcard(label,value,sub,tone=''){return '<div class="cr-health-card '+tone+'"><div class="cr-health-label">'+esc(label)+'</div><div class="cr-health-value">'+esc(value)+'</div><div class="cr-health-sub">'+esc(sub)+'</div></div>'}
function renderAll(){
 if(!D||painting)return;painting=true;
 const k=D.kpis||{},p=D.pending||{},s=D.sources||{},a=D.agenda||{},avail=a.coverage!=='NO_OPERATIONAL_REGISTRATIONS',pm=p.source_status!=='EMPTY_CANDIDATE_MASTER';
 const kh=q('kpis');if(kh)kh.innerHTML=
  kcard('🔧','Serviços em andamento',k.services_in_progress?.count,money(k.services_in_progress?.amount_cents)+' em execução','Em execução','blue')+
  kcard('▣','Aguardando pagamento',k.awaiting_payment?.count,money(k.awaiting_payment?.amount_cents)+' em aberto','Serviços concluídos','green')+
  kcard('▦','Visitas do dia',avail?k.visits_today?.count:null,a.note||'Agenda operacional','Hoje','purple')+
  kcard('▥','Orçamentos em fluxo',k.quotes?.count,k.quotes?.total_sampled!=null?k.quotes.total_sampled+' orçamentos lidos':'GestãoClick','Status reais','orange')+
  kcard('→','Agenda de amanhã',avail?k.agenda_tomorrow?.count:null,a.note||'Agenda operacional','Planejamento','blue')+
  kcard('←','Pendências de ontem',pm?k.pending_yesterday?.count:null,pm?'Banco Mestre':'Banco Mestre ainda sem alimentação operacional','Cobrança','red')+
  kcard('◷','Aguardando acerto',k.awaiting_adjustment?.count,money(k.awaiting_adjustment?.amount_cents)+' base','Medições / ajustes','amber')+
  kcard('!','Exceções de fonte',k.source_exceptions?.count,'Sinais objetivos vindos das fontes','Monitorar','red');
 const set=(id,v)=>{const x=q(id);if(x)x.textContent=num(v)};
 set('crV5AgToday',avail?a.today_count:null);set('crV5AgTomorrow',avail?a.tomorrow_count:null);set('crV5AgYesterday',pm?a.pending_yesterday:null);
 set('crV5AgNoConfirm',avail?a.without_confirmation:null);set('crV5AgNoOwner',avail?a.without_responsible:null);set('crV5AgIncomplete',avail?a.incomplete:null);
 if(q('crV5AgendaNote'))q('crV5AgendaNote').textContent=a.note||'Agenda operacional';
 const entries=Object.entries(D.quotes?.by_status||{}).sort((x,y)=>(y[1].count||0)-(x[1].count||0));
 if(q('crV5QuoteNote'))q('crV5QuoteNote').textContent=D.quotes?.ok?(D.quotes.quotes_sampled||0)+' orçamentos lidos • '+(D.quotes.live_estimated||0)+' em fluxo. Status preservados do GestãoClick.':'GestãoClick indisponível.';
 if(q('crV5QuoteStatuses'))q('crV5QuoteStatuses').innerHTML=entries.slice(0,10).map(([st,v])=>'<button class="cr-v5-status" type="button" data-v6-qstatus="'+esc(st)+'"><b>'+num(v.count)+'</b><span>'+esc(st)+'</span></button>').join('');
 if(q('boardSummary'))q('boardSummary').innerHTML=pcard('▥','Banco Mestre',pm?p.total_live:null,pm?'pendências vivas':'sem alimentação operacional homologada')+pcard('!','Vencidas',pm?p.overdue:null,pm?'exigem atenção':'fonte ainda não alimentada')+pcard('←','Ontem',pm?p.pending_yesterday:null,pm?'vencimento ontem':'fonte ainda não alimentada');
 if(q('homeHealth'))q('homeHealth').innerHTML=
  hcard('Banco de Dados',s.database?.ok?'Respondendo':'Indisponível',(s.database?.latency_ms??'—')+' ms',s.database?.ok?'ok':'')+
  hcard('Trello',s.trello?.ok?'Respondendo':'Indisponível',(s.trello?.latency_ms??'—')+' ms',s.trello?.ok?'ok':'')+
  hcard('GestãoClick',s.gestaoclick?.ok?'Respondendo':'Indisponível',(s.gestaoclick?.latency_ms??'—')+' ms',s.gestaoclick?.ok?'ok':'')+
  hcard('Agenda',s.agenda?.operational_records>0?'Fonte ativa':'Sem fonte operacional',num(s.agenda?.operational_records)+' registros não-QA',s.agenda?.operational_records>0?'ok':'')+
  hcard('Banco Mestre',s.pending_master?.records>0?'Alimentado':'Aguardando alimentação',num(s.pending_master?.records)+' registros',s.pending_master?.records>0?'ok':'')+
  hcard('API Executiva','V6 ativa','Somente leitura','blue')+
  hcard('Tempo de resposta',num(D.latency_ms)+' ms','Leitura executiva completa','blue')+
  hcard('Última verificação',D.checked_at?new Date(D.checked_at).toLocaleTimeString('pt-BR'):'—','Telemetria real','blue')+
  hcard('Ambiente','Candidata isolada','Produção não alterada','');
 const st=q('crV5State');if(st){st.className='cr-v5-state '+(FULL?'ok':'warn');st.textContent=FULL?'CANDIDATA V6 • detalhes autenticados':'CANDIDATA V6 • leitura real agregada'}
 const up=q('crHomeUpdated');if(up)up.textContent='Última atualização: '+new Date(D.checked_at||Date.now()).toLocaleString('pt-BR');
 setTimeout(()=>painting=false,0);
}
async function refresh(){try{D=await get(API+'?view=public-home&t='+Date.now());renderAll();if(sess()){try{FULL=await get(API+'?view=home&t='+Date.now());D=FULL;renderAll()}catch(_){FULL=null;renderAll()}}else FULL=null}catch(e){const st=q('crV5State');if(st){st.className='cr-v5-state warn';st.textContent='CANDIDATA V6 • '+e.message}}}
async function needFull(){if(FULL)return FULL;if(!sess())throw Error('Entre no acesso Diretor/Técnico para abrir os detalhes.');FULL=await get(API+'?view=home&t='+Date.now());D=FULL;renderAll();return FULL}
function agendaDetails(d){const a=d.agenda||{},host=q('crV5AgendaDetails');if(!host)return;const g=[['Hoje',a.items?.today||[]],['Amanhã',a.items?.tomorrow||[]],['Pendentes da agenda de ontem',a.items?.yesterday||[]]];host.innerHTML='<div class="cr-v5-agenda-list">'+g.map(x=>'<div class="cr-v5-agenda-col"><h4>'+x[0]+'</h4>'+(x[1].length?x[1].map(i=>'<div class="cr-v5-agenda-item"><b>'+esc(i.case_number||i.attendance_id||'Sem nº')+' • '+esc(i.title||'Compromisso')+'</b><br>'+esc(i.starts_at?new Date(i.starts_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Sem horário')+'<br>'+esc(i.responsible||'Sem responsável')+' • '+esc(i.status||'Sem status')+'</div>').join(''):'<div class="cr-v5-agenda-item">Nenhum registro nesta data.</div>')+'</div>').join('')+'</div>'}
function quoteDetails(d,filter=''){const host=q('crV5QuoteDetails');if(!host)return;const rows=(d.quotes?.items||[]).filter(x=>!filter||x.status===filter);host.innerHTML='<div class="cr-v5-actions" style="margin:0 0 8px"><button class="cr-v5-btn" data-v6-qstatus="">Todos os status</button><span class="cr-v5-state">'+esc(filter||'Todos')+'</span></div><table class="cr-v5-table"><thead><tr><th>Orçamento</th><th>Cliente</th><th>Status GestãoClick</th><th>Valor</th><th>Responsável</th><th>Data</th><th>Origem</th></tr></thead><tbody>'+rows.map(x=>'<tr><td><b>'+esc(x.case||'—')+'</b></td><td>'+esc(x.customer||'—')+'</td><td>'+esc(x.status||'—')+'</td><td>'+money(x.total_cents)+'</td><td>'+esc(x.responsible||'—')+'</td><td>'+esc(x.date||'—')+'</td><td><button class="cr-v5-btn" type="button" data-v6-case="'+esc(x.case||'')+'">Drill-down</button></td></tr>').join('')+'</tbody></table>'}
async function openCase(caseNo){const wrap=q('crV5Case'),body=q('crV5CaseBody');if(!wrap||!body)return;wrap.hidden=false;q('crV5CaseTitle').textContent=caseNo;body.innerHTML='<div class="cr-v5-warn">Consultando Trello + GestãoClick…</div>';try{const d=await get(API+'?view=case&case='+encodeURIComponent(caseNo)+'&t='+Date.now()),t=d.trello,g=d.gestaoclick||[];body.innerHTML='<div class="cr-v5-grid" style="padding:0"><div class="cr-v5-card"><h3>Trello • origem gerencial</h3>'+(t?'<p><b>'+esc(t.title||caseNo)+'</b></p><p>Status: '+esc(t.status||'—')+'<br>Valor: '+money(t.gross_cents)+'<br>Última atividade: '+esc(t.last_activity||'—')+'</p>'+(t.short_url?'<a class="cr-v5-btn primary" href="'+esc(t.short_url)+'" target="_blank" rel="noopener">Abrir origem no Trello</a>':''):'<p>Não localizado.</p>')+'</div><div class="cr-v5-card"><h3>GestãoClick • orçamento</h3>'+(g.length?g.map(x=>'<p><b>ID '+esc(x.external_id||'—')+'</b><br>'+esc(x.customer||'—')+'<br>Status: '+esc(x.status||'—')+'<br>Valor: '+money(x.total_cents)+'<br>Data: '+esc(x.date||'—')+'</p>').join(''):'<p>Não localizado.</p>')+'</div></div>'}catch(e){body.innerHTML='<div class="cr-v5-warn">'+esc(e.message)+'</div>'}}
async function hist(id){const wrap=q('crV5Case'),body=q('crV5CaseBody');wrap.hidden=false;q('crV5CaseTitle').textContent='Histórico';body.innerHTML='<div class="cr-v5-warn">Carregando trilha…</div>';try{const d=await get(MGMT+'?api=item-history&pending_id='+encodeURIComponent(id)),x=d.item||{},ev=d.events||[];q('crV5CaseTitle').textContent=x.title||'Histórico';body.innerHTML='<div class="cr-v5-card"><b>'+esc(x.public_status||x.status||'—')+'</b> • '+esc(x.priority||'—')+' • '+esc(x.responsible||'Sem responsável')+'<p>'+esc(x.next_action||'Sem próxima ação')+'</p></div><div class="cr-v5-expand" style="margin:10px 0 0">'+(ev.length?ev.map(e=>'<div class="cr-v5-agenda-item"><b>'+esc(e.event_kind||'EVENTO')+'</b> • '+esc(e.actor_name||e.actor_code||'')+' • '+esc(e.created_at?new Date(e.created_at).toLocaleString('pt-BR'):'')+'<br><small>'+esc(e.source_ref||'')+'</small></div>').join(''):'<div class="cr-v5-warn">Ainda não há eventos.</div>')+'</div>'}catch(e){body.innerHTML='<div class="cr-v5-warn">'+esc(e.message)+'</div>'}}
async function edit(id){const rows=q('crV5PendingBody')?.querySelectorAll('[data-v5-pid]')||[];if(!rows.length)return;const d=await get(MGMT+'?api=item-history&pending_id='+encodeURIComponent(id)),x=d.item||{},wrap=q('crV5Case'),body=q('crV5CaseBody');wrap.hidden=false;q('crV5CaseTitle').textContent='Editar pendência';body.innerHTML='<div class="cr-v5-toolbar" style="grid-template-columns:1fr 1fr"><label>Título<input id="v6eTitle" class="input" value="'+esc(x.title||'')+'"></label><label>Prioridade<select id="v6ePri" class="input">'+['P0','P1','P2','P3'].map(p=>'<option '+(p===(x.priority||'P2')?'selected':'')+'>'+p+'</option>').join('')+'</select></label><label>Categoria<input id="v6eCat" class="input" value="'+esc(x.category||'OPERACIONAL')+'"></label><label>Responsável<input id="v6eOwner" class="input" value="'+esc(x.responsible||'')+'"></label><label>Prazo<input id="v6eDue" class="input" type="datetime-local" value="'+esc(x.due_at?String(x.due_at).slice(0,16):'')+'"></label><label>Próxima ação<input id="v6eNext" class="input" value="'+esc(x.next_action||'')+'"></label></div><div class="cr-v5-actions"><button id="v6eSave" class="cr-v5-btn primary">Salvar alteração</button><span id="v6eMsg" class="cr-v5-state">Edição auditada</span></div>';q('v6eSave').onclick=async()=>{q('v6eMsg').textContent='Salvando…';try{await get(MGMT+'?api=update',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pending_id:id,title:q('v6eTitle').value,priority:q('v6ePri').value,category:q('v6eCat').value,responsible:q('v6eOwner').value,due_at:q('v6eDue').value?new Date(q('v6eDue').value).toISOString():null,next_action:q('v6eNext').value,idempotency_key:'ui-v6-'+id+'-'+Date.now(),source_ref:'central-executive-v6'})});q('v6eMsg').textContent='Salvo e auditado';setTimeout(()=>location.reload(),700)}catch(e){q('v6eMsg').textContent=e.message}}}
function enhancePending(){q('crV5PendingBody')?.querySelectorAll('.cr-v5-pitem').forEach(row=>{if(row.querySelector('[data-v6-phistory]'))return;const id=row.querySelector('[data-v5-pid]')?.getAttribute('data-v5-pid'),a=row.querySelector('.cr-v5-pactions');if(id&&a)a.insertAdjacentHTML('beforeend','<button type="button" data-v6-pedit="'+esc(id)+'">Editar</button><button type="button" data-v6-phistory="'+esc(id)+'">Histórico</button>')})}
window.addEventListener('click',async e=>{const t=e.target.closest?.('[data-v6-qstatus],[data-v6-case],[data-v6-pedit],[data-v6-phistory],#crV5AgendaOpen,#crV5QuotesOpen');if(!t)return;e.preventDefault();e.stopImmediatePropagation();try{if(t.id==='crV5AgendaOpen'){const d=await needFull(),h=q('crV5AgendaDetails');agendaDetails(d);h.hidden=!h.hidden}else if(t.id==='crV5QuotesOpen'){const d=await needFull(),h=q('crV5QuoteDetails');quoteDetails(d,qfilter);h.hidden=!h.hidden}else if(t.hasAttribute('data-v6-qstatus')){qfilter=t.getAttribute('data-v6-qstatus')||'';quoteDetails(await needFull(),qfilter);q('crV5QuoteDetails').hidden=false}else if(t.hasAttribute('data-v6-case'))await openCase(t.getAttribute('data-v6-case'));else if(t.hasAttribute('data-v6-pedit'))await edit(t.getAttribute('data-v6-pedit'));else if(t.hasAttribute('data-v6-phistory'))await hist(t.getAttribute('data-v6-phistory'))}catch(err){alert(err.message)}},true);
function init(){['kpis','boardSummary','homeHealth','crV5QuoteStatuses'].forEach(id=>{const el=q(id);if(el)new MutationObserver(()=>{if(D&&!painting)setTimeout(renderAll,0)}).observe(el,{childList:true})});const pb=q('crV5PendingBody');if(pb)new MutationObserver(enhancePending).observe(pb,{childList:true,subtree:true});refresh();setInterval(refresh,30000);setInterval(enhancePending,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();